extends Node
class_name AudioZoneTestMaximumSchizoPartOne

const AUDIO_ZONE_SCENE_PATH: String = "res://godot/Test/SchizophrenicGodotTests/AutoGeneratedAudioZoneScene.tscn"


func create_and_save_audio_zone_scene() -> void:
    if ResourceLoader.exists(AUDIO_ZONE_SCENE_PATH):
        return

    var audio_zone = AudioZone.new()
    var packed_scene = PackedScene.new()
    packed_scene.pack(audio_zone)
    var save_result = ResourceSaver.save(packed_scene, AUDIO_ZONE_SCENE_PATH)
